baseURL: "https://www.example.com/"
theme: "up-business-theme"
languageCode: "en-us"

title: "SPIC MACAY"

googleAnalytics: ""

summaryLength: 20

params:
  colors:
    mainColor: "red"
  title: "SPIC MACAY"
  description: "SPIC MACAY - 10th International Convention"
  images:
    - "images/hero-image.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    dribbble: "#"
    instagram: "#"
    facebook: "#"
    twitter: "#"

  location:
    - "3891 Ranchview Dr. Richardson, California 62639"
    - "4517 Washington Ave. Manchester, Kentucky 39495"

  contact:
    - "trungkienspktnd@gamail.com"
    - "207.555.0119"

  copyright: "© 2022 Up Business All Rights Reserved"

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "About Us"
      url: "/about"
      weight: 2

    - name: "Artists"
      url: "/artists"
      weight: 3

    - name: "Event"
      url: "/event"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

  buttons:
    - name: "SPIC MACAY HOME"
      url: "/#"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "About us"
      url: "/about"
      weight: 2

    - name: "Artists"
      url: "/artists"
      weight: 3

    - name: "Pricing"
      url: "/#"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"
